### ISSUE TITLE
undefined method 'sysread' with 0.1.4

### ISSUE THREAD

**Issue by DanielRedOak** [logstash-plugins/logstash-input-lumberjack#7]
Using a basic config with normal key and cert I see this in debug logs and then a crash:

NoMethodError: undefined method `sysread' for nil:NilClass
     run at /opt/logstash/vendor/bundle/jruby/1.9/gems/jls-lumberjack-0.0.21/lib/lumberjack/server.rb:225
  invoke at /opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-lumberjack-0.1.4/lib/logstash/inputs/lumberjack.rb:71

Worked in 1.5.0.beta1 with the same config so something weird is going on that I am more that willing to help track down.

**Comment by DanielRedOak** [comment]
Seems related to this code

```go
def run(&block)
      while true
        # TODO(sissel): Ack on idle.
        # X: - if any unacked, IO.select
        # X:   - on timeout, ack all.
        # X: Doing so will prevent slow streams from retransmitting
        # X: too many events after errors.
        @parser.feed(@fd.sysread(16384)) do |event, *args|              <<<<<<<<  right here
          case event
          when :window_size; window_size(*args, &block)
          when :data; data(*args, &block)
          end
          #send(event, *args)
        end # feed
      end # while true
    rescue EOFError, OpenSSL::SSL::SSLError, IOError, Errno::ECONNRESET
      # EOF or other read errors, only action is to shutdown which we'll do in
      # 'ensure'
    ensure
      close rescue 'Already closed stream'
    end # def run
```

**Comment by DanielRedOak** [comment]
Something strange is going on. I'm thinking maybe something DNS related but still am digging

**Comment by DanielRedOak** [comment]
This actually looks to be a regression somewhere, probably in the LSF code.  What is happening is that I have a node behind an ELB in Amazon with a health check on the LJ port.  Health check comes along, opens and then closes a session on the port causing the Lumberjack input to crash Logstash :(

**Comment by jordansissel** [comment]
@DanielRedOak that exception will cause it to retry, not do anything further.

If I test this myself based on your report:

```
ruby -I./lib -rlumberjack/server -e 'p Lumberjack::Server.new(:ssl_certificate => "./lumberjack.crt", :ssl_key => "./lumberjack.key", :port => 3333).accept'
```

This runs a lumberjack server instance and waits for the first good connection.

Test 1: No data sent

If I connect with `nc localhost 3333` and terminate it, the server stays because no connection is accepted.

Test 2: Garbage

If I send garbage and then disconnect, nothing bad happens and the server stays up waiting for that first good ssl connection:

```
while true; do dd if=/dev/urandom bs=4k count=2 | nc localhost 3333; sleep 0.1; done
```

Test 3: Do a good ssl connection 

```
openssl s_client -connect localhost:3333
```

Then the `.accept` call finally returns:

```
#<Lumberjack::Connection:0x007fc499817940 @ ....
```

I can't reproduce this in MRI

**Comment by jordansissel** [comment]
Redoing my previous comment's tests with JRuby 1.7.19 and I also am successful. No bug reproduction :(

**Comment by jordansissel** [comment]
I'm not disputing your report, btw, I believe it to be a bug. I can't figure out how to reproduce it, though. Frustrating :P

**Comment by DanielRedOak** [comment]
Seems that the Lumberjack Library packaged with 1.5.0.rc1 doesnt contain your retry fix from 2 days ago that adds the 'retry' so thats likely the whole issue here.  I manually added that line and can see the .accept retry and doesn't crash Logstash so I can re-package the tar and move on :smiley: 

Also, does retrying indefinitely affect anything in terms of performance or the like?  Ie does it keep retrying keep iterating that code block for that specific connection until it disconnects?  Just wondering if that opens things up to attacks :)

**Comment by DanielRedOak** [comment]
def accept(&block)
      begin
       puts @tcp_server.inspect
        puts @ssl_server.inspect
        fd = @ssl_server.accept
      rescue EOFError, OpenSSL::SSL::SSLError, IOError
        # ssl handshake or other accept-related failure.
        # TODO(sissel): Make it possible to log this.
        retry    <<--the missing line from the 1.5.0.rc1 tar
      end
      if block_given?
        block.call(fd)
      else
        Connection.new(fd)
      end
    end

**Comment by jordansissel** [comment]
Ouch. This explains so much.

**Comment by jordansissel** [comment]
@suyograo let's get this fix into 1.5.0RC2 if possible?

**Comment by jordansissel** [comment]
jls-lumberjack v0.0.22 gem pushed now.

**Comment by jordansissel** [comment]
@DanielRedOak I wonder if we can try an experiment.

Since I've published a new version of jls-lumberjack, can you try reinstalling the lumberjack input and outputs?

```
bin/plugin uninstall logstash-input-lumberjack
bin/plugin uninstall logstash-output-lumberjack
bin/plugin install logstash-input-lumberjack
bin/plugin install logstash-output-lumberjack
```

This may upgrade jls-lumberjack. It's worht a shot.

**Comment by DanielRedOak** [comment]
Yep, seems to update the installed gem and includes your code changes.  I'm going to cheat since I have everything behind ansible in AWS and re-tar a patched version but I appreciate the help.  

Also just as an FYI in case it comes up, with the crash of the lumberjack input I was seeing a logged failure of the syslog udp listener.  Thats what led me to turn on debugging and see the lumberjack error which was not being logged by default.  Here is the other failure that led me on the hunt in case anyone else sees something similar:

```
syslog listener died {:protocol=>:udp, :address=>"0.0.0.0:1514", :exception=>#<SocketError: recvfrom: name or service not known>, :backtrace=>["/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-syslog-0.1.3/lib/logstash/inputs/syslog.rb:138:in `udp_listener'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-syslog-0.1.3/lib/logstash/inputs/syslog.rb:117:in `server'", "/opt/logstash/vendor/bundle/jruby/1.9/gems/logstash-input-syslog-0.1.3/lib/logstash/inputs/syslog.rb:97:in `run'"], :level=>:warn, :file=>"logstash/inputs/syslog.rb", :line=>"120", :method=>"server"}
```

Thanks again for looking into this with me!

**Comment by suyograo** [comment]
https://github.com/elasticsearch/logstash/pull/2787

**Comment by suyograo** [comment]
@DanielRedOak would you be willing to test a patched tar version which I can produce in next 10 minutes? this will have the fix

**Comment by DanielRedOak** [comment]
Yea, no problem.  Just let me know where to grab it from

**Comment by suyograo** [comment]
Released RC2 :)
